export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{vue,js,ts}'],
  theme: {
    extend: {
      colors: {
        'tertiary-container': '#0077a6',
        'on-primary-fixed-variant': '#93000d',
        'surface-container': '#ffe9e6',
        'tertiary-fixed-dim': '#83cfff',
        'on-error-container': '#93000a',
        background: '#fff8f7',
        'on-surface-variant': '#5c403d',
        error: '#ba1a1a',
        'surface-tint': '#bd1119',
        'on-primary-container': '#fff1ef',
        'primary-fixed': '#ffdad6',
        'primary-container': '#d62828',
        'secondary-container': '#d6e0f3',
        primary: '#b20112',
        'error-container': '#ffdad6',
        'on-tertiary-container': '#ebf5ff',
        'on-tertiary-fixed-variant': '#004c6c',
        'on-primary-fixed': '#410002',
        'on-secondary-fixed': '#121c2a',
        'surface-bright': '#fff8f7',
        'on-secondary-fixed-variant': '#3d4756',
        surface: '#fff8f7',
        'surface-container-high': '#ffe2de',
        'on-secondary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'on-surface': '#281716',
        'on-secondary-container': '#596373',
        'inverse-on-surface': '#ffedea',
        'surface-variant': '#fbdbd8',
        'tertiary-fixed': '#c7e7ff',
        'outline-variant': '#e5bdb9',
        'on-primary': '#ffffff',
        'on-background': '#281716',
        outline: '#906f6b',
        'surface-container-highest': '#fbdbd8',
        'secondary-fixed-dim': '#bdc7d9',
        secondary: '#555f6f',
        'primary-fixed-dim': '#ffb4ab',
        'on-tertiary-fixed': '#001e2e',
        'surface-dim': '#f2d3cf',
        tertiary: '#005d83',
        'secondary-fixed': '#d9e3f6',
        'on-tertiary': '#ffffff',
        'surface-container-low': '#fff0ee',
        'inverse-surface': '#3f2c2a',
        'on-error': '#ffffff',
        'inverse-primary': '#ffb4ab',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        lg: '24px',
        'container-max-width': '1200px',
        'margin-mobile': '16px',
        '3xl': '64px',
        xl: '32px',
        gutter: '16px',
        'margin-desktop': '32px',
        '2xl': '48px',
        xs: '4px',
        sm: '8px',
        md: '16px',
        unit: '4px',
      },
      maxWidth: {
        'container-max-width': '1200px',
        lg: '32rem',
        xl: '36rem',
        '2xl': '42rem',
        '3xl': '48rem',
        '4xl': '56rem',
      },
      fontFamily: {
        'label-md': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'headline-xl': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
      },
    },
  },
}
