import { defineStore } from 'pinia'

export const useSiteContentStore = defineStore('siteContent', {
  state: () => ({
    navItems: [
      { label: 'Home', to: '/' },
      { label: 'About', to: '/about' },
      { label: 'Programs', to: '/programs' },
      { label: 'Services', to: '/services' },
      { label: 'Gallery', to: '/gallery' },
      { label: 'Contact', to: '/contact' },
    ],
    programs: [
      {
        title: 'Basketball',
        tag: 'Sports',
        duration: '12 Weeks',
        ages: 'Ages 13-19',
        description: 'Master the fundamentals of basketball while building teamwork, discipline, and physical fitness.',
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB4rBToFm7EGTxsKOgV8K5LZSpZawnwVgxZ1KyRur7Kb-zupnkp54IACmyCwu8qqTOo_A_liFUZym9g9WEW1oS3PZ6Io9L7C1q5tNJdyA2GQEV8kJD5LX1852s0bD1O41Y7r1m-n8PQawGaY0-rzf4ZWLO0_EehhpATcrm8uGjVNIbwU-_eN4X4PGmFpQAHfvg1FYgRhJD0IWaabW4ZDuf_TIcsWG3ROzvKDk0Tkww0ZDRXmhgxNcMXs0YSjAm2EUVSyf_SVip1-Qg',
        tagClass: 'bg-tertiary text-on-tertiary',
      },
      {
        title: 'Computer Training',
        tag: 'Vocational',
        duration: '6 Months',
        ages: 'Ages 16+',
        description: 'Essential digital literacy skills, office productivity tools, and an introduction to the digital economy.',
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuARjbzTwUIHJqkdqLPQLMZR36gNQgi1CHITbwe-2LPKNskxVaC784Y8SQA1XGbKfoZ6_Isi1sTOae3JXlEWN-TWz9fRn_caXThM15SrXi6HC8Mc2w0Z_LxGJp03tum4Hyhzf0t7Ng4NrF93sqC4i5nMZS0CTvz8LWdGwL_8x_Vczn9R8uuKAIfF1eqAI-HbKIpYssv4H-ionGLiDmbs-kRGvBx9e8Nuii8HGdaoMkl-eRx14Xve324iHTswKj0cogpb7UKpgTPObHc',
        tagClass: 'bg-primary-container text-on-primary-container',
      },
      {
        title: 'Leadership',
        tag: 'Development',
        duration: 'Ongoing',
        ages: 'Ages 15-25',
        description: 'Developing community-conscious leaders through civic engagement and project management.',
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBm7uTBufx_nYb5hqbQ9iVsKLhJMwuKkzjg5wn-Y6LHsijKDqJi1L1vIxkm-RlQshZ7e_Df5BLkBNBdyJKEz69-BQ0PwUFOw7KYq-eN4FuyDi9H7yNvqm1zswQJsWZerSmq9omFGEWGGjjEM0RaNdsBEzxfyG32uMWPxP-O_TF5N7jbb9xEyYqpf4OnG_ml_DzWLeq3-GSKMW4aFB2bl2pBoquLZVGH3vQUnBQoxUh1QTZ3k6WyJRL6AxzL9PvOrMq7aHSJu4tPPPg',
        tagClass: 'bg-tertiary-container text-on-tertiary-container',
      },
      {
        title: 'Entrepreneurship',
        tag: 'Business',
        duration: '4 Months',
        ages: 'Ages 18-30',
        description: 'Transforming ideas into reality. Learn business planning, financial literacy, and marketing basics.',
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC4KMJdnjO0LgDTGOjJMDtF--GBTvfEkurfofCE7ZVJlx-DcrUyA-QnJd9vRhu4I7Cr-whPZJvQy1HM2heo2O9xT7IAcnxyuXhzAexq0kZHjcgwdIQCSXBpKl8zJYuxcJ1NHrL0ezZd8vNUWpDc1QvqunAqlF6n8E2nG_ZNL8feC79kpUd0FanwCW4tQtroEYBTcH3ptpXKnJVqR3Tw6G-7MMKuxPvSRSVZrt9lp_gGhe5nWrMgSkpFzAw-0i9ajIfGHe_A2XmGFEw',
        tagClass: 'bg-primary-container text-on-primary-container',
      },
      {
        title: 'Cake Baking',
        tag: 'Vocational',
        duration: '8 Weeks',
        ages: 'Ages 16+',
        description: 'Learn the art of baking and pastry design. A sweet path towards financial independence and creative expression.',
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBE1N2da-imIRMw9i4V5NU5iZTfrFFcdLpa9pJfrCjW2vYf5MUHw4oMTyiaRZpIBLmonF6XpYkWyxJeApI2oJfgHwsRyhz-olIq22GISSFVzoN4t03KMvV8m1NGIe_iKdC0M7HAk3L_rvIiO6_D4nbY5dRY31zn_QwpWnT8Q4_USf61Uryfnt2oCQK1qu6kXz3OdEq_B5lU74NZ-ZRSO3sn7YKvkwAzCDTw5MP8NUIiquvzouMNBiWv9wjdSUllvkaurSm8VUd6j1Y',
        tagClass: 'bg-surface-container-highest text-on-surface',
      },
      {
        title: 'Arts & Creativity',
        tag: 'Arts',
        duration: 'Seasonal',
        ages: 'Ages 10-18',
        description: 'Exploring visual arts, painting, and craft-making to foster self-expression and cultural pride.',
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC5X0vg-mf6TU9QL1SBl_SATD3saQB35eK54tP2S8o5d7GF8peiBm6IFvoy37A5XHfydBvTPO2HVpkQTB0NMHLu_vgAeFni3rWyEVdsoKkPdAf_ZStU20bSzgj3gBMoZhemJvQ2tz5AE6uZiQAjRaSRYHyx53nyZVQXm60r5LlysNOj9gxBFfPemg4CuznBV-vtNSqU9uVXKy6mmIssNGi6wewaGtnZk2Ao_1qMjBLM-g1UQFezGcjmnpWVSVPbpzrJOantfE1IAXc',
        tagClass: 'bg-tertiary text-on-tertiary',
      },
      {
        title: 'Beauty Pageant',
        tag: 'Social',
        duration: 'Annual',
        ages: 'Ages 17-25',
        description: 'Building self-confidence, public speaking skills, and personal grooming through our annual youth showcase.',
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDZDwxXnlbL4gkP5r-LJ29y7q1xpv7NpTmFyUK8lMr5KiFepZqgE4WR3gUCUb0B-NzaAXR48Fb5IHaeu-I409YNOMrZK9ADZDdrVI07y4uTRQ56O_FByXLXUptkY5cO0cmlD82Ov9NWFdWWajoqJ4mT6ZNblSmiYrnArE86yf6_fPPsGERits2Dtzj7ZGSbRfjL9cemZ9FDs11aQu0pfK3nCmSxj3YD_2jfMAc8nATtz6MA8XqHiJCdpDv0X-2xTDhPslPWcvwNIs8',
        tagClass: 'bg-primary-container text-on-primary-container',
      },
      {
        title: 'Life Skills',
        tag: 'Life Skills',
        duration: '6 Weeks',
        ages: 'All Ages',
        description: 'Crucial skills for daily life: health awareness, emotional intelligence, and financial responsibility.',
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuADAMi6zkobvjy-uuG_bNrOFBOY9VuOATJYSqSq7GxN8Py4_i2OPOlNDntowWBSiGI5yB_NJlrhVq_aD9vAC3JENrWEdtyTaRyiPwTVXqaNdlCp95LzuC2g1XoCy1gzyAuo__MOG6L04begt1xokD2pt22tkWNsIKUHO_Iz3JQ9MQHT9BiCuzjqhYb1PDsIN7L2_vwM896iNxquKw-xEu6ZTodpS97dT9E0nXd_cRfEvlCc1ju3xity7EVpcUN5lnscLsVI8QeQq0U',
        tagClass: 'bg-tertiary-container text-on-tertiary-container',
      },
    ],
    galleryItems: [
      ['basketball', 'Sports', 'Championship Training', 'masonry-tall', 'https://lh3.googleusercontent.com/aida-public/AB6AXuD6n5MUv7LtpiVPL5XIFfR4ABp4VHxu8R-_hgmFZ6vUfMv0cTIzXZCbF0e8pqj_hDLYMzSMf29ZbNvti_KuC2vMmO_6e_pEOs0p0NNt_n4-bqx26cS91xcY420PPoITppyn7CB1yq6umG0J3h5XALtOz1aot2m710OPAnTnvBTIYR8PrBCS_8wWM1I0Z8_s_SkrOzPcvGccPMvE8IdeX-z-dJ8OxP6DJSwwh84m3_IrGz6R0Ixm98nRDyg2N4tUGWxPzu2MpjgAY0M'],
      ['computer', 'Tech', 'Digital Literacy', '', 'https://lh3.googleusercontent.com/aida-public/AB6AXuDCKQDkgo2AeN9u2OLuPx6un707qQeEBZMR2mPU6hEnvi8De90cG2YWDShgr7_zcFyRDrWvCZ7X6hwNa4sQmceEcBaBcr8_bhdQ1eoxS6Kt541dGxjv5S5B-RAmGgAgasEghBhnNXjYq44CHyUqTQlJmpHpkO27usk1rKwtDs3JZw_5c0nFO0LkF--_iUHNvKnbYCCufbkdajY-HwV3fbc8497GEg00SMXRcdewFQCIQIMkjMhxdm0GdGEqNt5WPKTX1oF8sLRkA0c'],
      ['leadership', 'Empowerment', 'Future Leaders Forum', 'masonry-wide', 'https://lh3.googleusercontent.com/aida-public/AB6AXuAsrotYfUcySmiNoPWU8Kc8RZBAGSU4wDzD2GkX5iwc3ag_nk0gSo1qbFA0PNM7sBathYgXRuRRstUXUldIdAe0yL8h6ChRtpiBe474WtrR8bu3IhpJE9wH7aNbFLGMeHEqPXEncp0C_cVMvjiw-k3Kp9XW7irhhGlCp_U9Tb5uyTsBex0DI9T--cnaR5f4geM0yP44xPKryerzo8K1inB5O4Hs9nN_Wh2l_f0G5-DbARRWzjvdLZwLg8HiRxdtX01sCVCduk6b3D4'],
      ['entrepreneurship', 'Business', 'Youth Market Day', 'masonry-tall', 'https://lh3.googleusercontent.com/aida-public/AB6AXuCcAyxZeH9tcH78r0Bq0jHwc0jBfstOVKs0JiuV2kS6fM032_xYsQ9EGfOYY78tR-DLC19yIo_w9CbiFbgcWRa4MAEwDTNF7ESbhDs8HEwGNCo0LjlL94gERHTup2VXSoM0wkE-HYzwLrYsSl8UWCDzw1qYaKuc5Kkp0UTcmJSXzNiqrImyTZ-xmniFcxXO25kM1bn13Gv6C5vPikj0P2kFYMLH8SHuptW56PLLeroNneTtsGp2y_zXa-7_Ykro_9cYUDIeHHFej-o'],
      ['art', 'Creativity', 'Murals for Peace', '', 'https://lh3.googleusercontent.com/aida-public/AB6AXuBbqncVA6b8HMzSpTFWnRW1Rw2JjKgBnPZR6-skx7gyem_t7FvzJTF8q-LbwrZwlE79GeWabOME7dKAGQcwYOABZ6nT7I7GEGjVA6qgs6GopGKOT91p67QiHWQLEKsdJkt75nCjG5vrXFvI99XMY0hmTjFQGmKC1Hgi1LxEQp6rOOmPmUBmuJsRDf00-aaLQYgdV0C5oQKojZ34E2e57ptvjpyHKW2SHt5X3cFMajSNIArgSgDbam0-YQN9cNkOgwgi7umpsSDd0mY'],
      ['community', 'Community', 'Outreach Program', '', 'https://lh3.googleusercontent.com/aida-public/AB6AXuDI-IKEqbG_yQ3BvCAb07lNHezNzN1cWAWCozajz_8nSrJbiYW-rIlJfKiEXwflWtNZHj5f-0YYgohZeele4FN4ymy1Evs_pVWUo4brh3xZc6Mrm7NBuY295_3c1kqkoyQLZaQH2OG_aC6kmZ5s5O-inNEJDq6Q_nIQPKCMiPiYvMPXlMp_qjCAhtEpYcBY_mwYJfBK3RoImxW9kfgzpRuz-XAVLOrYtKjO_-jhezmBpSbN2Lzph-JUbLU7Rn0wQmMZplORUS2rOoE'],
    ],
  }),
})
